/**
 * Models carrying a tenantId column, generated from prisma/schema.prisma.
 *
 * Anything NOT listed here is global -- currently only Role and Tenant -- and
 * is never tenant-filtered. If you add a model with a tenantId column, add it
 * here too, or its rows will be visible to every factory.
 */
export const TENANT_SCOPED_MODELS: Record<string, true> = {
  user: true,
  biometricCredential: true,
  employee: true,
  department: true,
  leaveRequest: true,
  device: true,
  attendanceRecord: true,
  dailyAttendanceLog: true,
  product: true,
  stockLevel: true,
  warehouse: true,
  stockMovement: true,
  supplier: true,
  purchaseOrder: true,
  purchaseOrderItem: true,
  goodsReceipt: true,
  goodsReceiptItem: true,
  customer: true,
  salesOrder: true,
  salesOrderItem: true,
  salesPayment: true,
  account: true,
  journalEntry: true,
  journalEntryLine: true,
  importJob: true,
  payrollRun: true,
  payrollItem: true,
  payrollReceipt: true,
  payrollInput: true,
  employeeSalary: true,
  employeeAdvance: true,
  deletedRecordHistory: true,
  employeeInsurance: true,
  employeeBonus: true,
  employeePenalty: true,
  terminationRecord: true,
  financialSettlement: true,
  rehireRecord: true,
  bus: true,
  busPassenger: true,
  auditLog: true,
  notification: true,
  productBatch: true,
  batchStockLevel: true,
  expiryAlertRule: true,
  warehouseZone: true,
  storageBin: true,
  putawayTask: true,
  taxRate: true,
  priceTier: true,
  productPrice: true,
  purchaseInvoice: true,
  purchaseInvoiceItem: true,
  landedCost: true,
  purchasePayment: true,
  costHistory: true,
  salesInvoice: true,
  salesInvoiceItem: true,
  deliveryNote: true,
  deliveryNoteItem: true,
  cycleCount: true,
  cycleCountItem: true,
  qualityInspection: true,
  pickList: true,
  pickListItem: true,
  carrier: true,
  shipment: true,
  package: true,
  packageItem: true,
  integrationConnection: true,
  integrationSyncLog: true,
  webhookEndpoint: true,
  accountMapping: true,
  tenantEntitlement: true,
  userEntitlement: true,
  tenantSubscription: true,
  representative: true,
  repRoute: true,
  repCustomer: true,
  repProduct: true,
  repStock: true,
  repStockMovement: true,
  repSale: true,
  repSaleItem: true,
  repCollection: true,
  repReturn: true,
  repSettlement: true,
};

export function isTenantScoped(model?: string): boolean {
  if (!model) return false;
  const key = model[0].toLowerCase() + model.slice(1);
  return TENANT_SCOPED_MODELS[key] === true;
}
